<?php
namespace Kunsal\Laramodula;

use Illuminate\Support\ServiceProvider;
use Kunsal\Laramodula\Commands\GenerateModule;

class LaramodulaServiceProvider extends ServiceProvider
{
    public function boot() {
        $this->commands([GenerateModule::class]);
        $this->loadRoutesFrom(__DIR__.'/web.php');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
