<?php
namespace Kunsal\Laramodula;

use Illuminate\Support\ServiceProvider;
use Kunsal\Laramodula\Commands\GenerateModule;

class LaramodulaServiceProvider extends ServiceProvider
{
    public function boot() {
        $this->commands([GenerateModule::class]);
        $modules_path = app_path('Modules');

        if (!file_exists($modules_path)) {
            mkdir($modules_path);
        }
        $modules = scandir($modules_path);

        foreach ($modules as $module) {
//            // Autoload routes
//            if(is_dir($routes_path = $modules_path.'/'.$module.'/Http')){
//                $this->loadRoutesFrom($routes_path);
//            }
            // Autoload views
            if(is_dir($views_path = $modules_path.'/'.$module.'/Resources/Views')){
                $this->loadViewsFrom($views_path, $module);
            }
            // Autoload Translations
            if(is_dir($translation_path = $modules_path.'/'.$module.'/Resources/Lang')){
                $this->loadTranslationsFrom($translation_path, $module);
            }
            // Autoload Migrations
            if(is_dir($migration_path = $modules_path.'/'.$module.'/Models/Migrations')){
                $this->loadMigrationsFrom($migration_path);
            }
        }
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
